- name: Install epel repo
  yum: name=epel-release state=installed

- name: Install Nginx
  yum: name=nginx state=installed
  notify:
    - Start Nginx

- name: Remove default nginx vhost
  file: path=/etc/nginx/conf.d/default.conf state=absent
